name: Publish Website to Web Hosting

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy website every commit
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # You can specify your preferred Flutter version here

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          flutter pub get  # Install necessary Flutter dependencies

      - name: Build Flutter web app
        run: |
          flutter build web  # Build the Flutter web app

      - name: FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}  # Use secrets for sensitive info
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps  # Ensure the protocol is 'ftps' for secure transfer
          port: 21
          local-dir: './build/web'  # Path to the Flutter web build output
