name: Build and Deploy Flutter Web on Cpanel

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.2.7'  # Adjust according to your Flutter version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Build Flutter web app
      - name: Build Flutter web app
        run: flutter build web

      # Step 5: Deploy to FTP server
      - name: FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}  # Use secrets for sensitive info
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps  # Ensure the protocol is 'ftps' for secure transfer
          port: 21
          local-dir: './build/web'  # Path to the Flutter web build output
